config/routes.rb
get 'projects/:project_id/issues_kanban', :to => 'issues_kanban#index'
get 'issues_kanban', :to => 'issues_kanban#index'

app/controllers/issues_kanban_controller.rb
class IssuesKanbanController < ApplicationController
  unloadable
  helper :issues
  include IssuesHelper

  helper :queries
  include QueriesHelper

  before_filter :find_project, :only => [:index]
  before_filter :find_version, :only => [:index]
  before_filter :find_issues,  :only => [:index]

  def index
    @statuses = IssueStatus.all(:order => "position asc")

    @status_estimated_hours = {}
    @statuses.each do |status|
      @status_estimated_hours[status.id] = sprintf("%.2f",@issues.find_all { |x| x.status_id == status.id }.map(&:estimated_hours).map(&:to_f).sum)
    end
    
    @assignees = @issues.find_all { |x| x.assigned_to_id != nil }.map(&:assigned_to).uniq.to_a.sort { |a,b| b.id.to_i <=> a.id.to_i }
    @assignees << nil if @issues.any? { |x| x.assigned_to_id == nil }

  rescue ActiveRecord::RecordNotFound
    render_404
  end

  private

  def find_project
    if project_id = (params[:issue] && params[:issue][:project_id]) || params[:project_id]
      @project = Project.find(project_id)
    end
  end

  def find_version
    return unless @project

    @versions = @project.shared_versions || []
    @versions += @project.rolled_up_versions.visible if @with_subprojects
    @versions = @versions.uniq.sort
    @versions.reject! {|version| version.closed? || version.completed? } unless params[:completed]

    if params[:version]
      @version = @project.shared_versions.find(params[:version])
    end
  end


  def find_issues
    issues_finder = { :include => [:assigned_to, :tracker, :priority, :category, :fixed_version], :order => "issues.assigned_to_id DESC, enumerations.position DESC" }

    if @project
      conditions = {}
      if @version
        conditions[:fixed_version_id] = @version.id
      end
      issues_finder[:conditions] = conditions

      @issues = @project.issues.find(:all, issues_finder)
    else
      retrieve_query

      @query.group_by = nil
      @issues = @query.issues(issues_finder)
    end
  end

end

app/helpers/issues_kanban_helper.rb
module IssuesKanbanHelper
  def color_of_user(x)
    "rgb(" + (Digest::MD5.hexdigest(x.login)[0..5].split(/(..)/).select { |x| x != "" }.map { |x| 255 - (x.to_i(16) % 64) }).to_a.join(",") + ")"
  end

  def status_classes(status)
    "section issue-status issue-status-#{status.id} #{status.is_closed ? " is_closed" : '' } #{status.is_default ? " is_default" : ''}"
  end

  def user_section_title(user, status)
    user_id = user ? user.id : 0
    (user ? link_to_user(user) : "(Someone)") + " (#{user_estimated_hours(user, status)} hr)";
  end

  def user_estimated_hours(user, status)
    hour_format(user_issues(user, status).map { |x| x.estimated_hours.to_f }.sum)
  end

  def user_issues(user, status)
    user_id = user ? user.id : nil
    @issues.find_all { |x| x.assigned_to_id == user_id && x.status_id == status.id }.to_a
  end

  def hour_format(time)
    sprintf("%.2f", time).to_f
  end


  # Based on https://github.com/henrik/slugalizer/blob/master/slugalizer.rb
  def slugalize(text, separator = "-")
    separators = %w[- _ +]
    unless separators.include?(separator)
      raise "Word separator must be one of #{separators}"
    end
    re_separator = Regexp.escape(separator)
    result = decompose(text.to_s)
    result.gsub!(/[^\x00-\x7F]+/, '') # Remove non-ASCII (e.g. diacritics).
    result.gsub!(/[^a-z0-9\-_\+]+/i, separator) # Turn non-slug chars into the separator.
    result.gsub!(/#{re_separator}{2,}/, separator) # No more than one of the separator in a row.
    result.gsub!(/^#{re_separator}|#{re_separator}$/, '') # Remove leading/trailing separator.
    result.downcase!
    result
  end

  def decompose(text)
    if defined?(ActiveSupport::Multibyte::Handlers) # Active Support <2.2
      ActiveSupport::Multibyte::Handlers::UTF8Handler.normalize(text, :kd).to_s
    else # ActiveSupport 2.2+
      ActiveSupport::Multibyte::Chars.new(text).normalize(:kd).to_s
    end
  end
end

app/views/issues_kanban/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'flick/jquery-ui-1.8.4.custom.css', :plugin => :redmine_issues_kanban %>
    <%= stylesheet_link_tag 'issues-kanban', :plugin => :redmine_issues_kanban %>
    <%= javascript_include_tag 'jquery-1.4.2.min.js', 'jquery-ui-1.8.4.min.js', :plugin => :redmine_issues_kanban %>
    <script type="text/javascript">
        jQuery.noConflict();

        (function($) {
            var authenticity_token = <%= form_authenticity_token.to_json.html_safe %>;
            var authenticity_token_name = <%= request_forgery_protection_token.to_json.html_safe %>;

            $(function() {
                $("#issues-kanban").scrollLeft($('.issue-status:first').width() * 0.9);

                $(".user-issues").sortable({
                    items: "div.issue",
                    placeholder: 'ui-state-highlight',
                    forcePlaceholderSize: true,
                    connectWith: '.user-issues',
                    receive: function(event, ui) {
                        var issue_id = ui.item.attr('class').match(/issue-(\d+)/)[1];
                        var assigned_to_id = $(ui.item).parent('.user-issues').attr("class").match(/user-id-(\d+)?/)[1]
                        var status_id = $(event.target).parent('.issue-status').attr("class").match(/issue-status-(\d+)/)[1];

                        var data = {

                            'issue[assigned_to_id]' : assigned_to_id,
                            'issue[status_id]': status_id,
                            '_method': "put"
                        };
                        data[authenticity_token_name] = authenticity_token;

                        ui.item.addClass('updating');
                        $.ajax({
                            'type': 'post',
                            'data': data,
                            'url': '<%= issues_path %>/' + issue_id,
                            'success': function() {
                                ui.item.removeClass('updating');
                            }
                        });
                    }
                }).disableSelection();
            });

        }(jQuery));
    </script>
<% end %>

<div id="issues-kanban-version-query" class="nav">
  <%= link_to "Issue List", {:controller => "issues", :action => "index", :project_id => @project} %>

  <% if @versions && @versions.size > 0 %>
      <span>Versions:</span>
      <%= link_to "All", {:controller => "issues_kanban", :action => "index", :project_id => @project} %>
      <% @versions.each do |version| %>
          <%= link_to version.name, {:controller => "issues_kanban", :action => "index", :project_id => @project, :version => version} %>
      <% end %>
  <% end %>
</div>

<% form_tag({}) do -%>
<%= hidden_field_tag 'back_url', url_for(params) %>
<div id="issues-kanban">
  <% @statuses.each do |status| %>
      <div class="<%= h status_classes(status) %>">
        <h2 class="title"><%= h status.name %> (<%= @status_estimated_hours[status.id] %> hr)</h2>

        <% ordered_assignees = [] %>
        <% @assignees.each do |user| %>
            <% ordered_assignees << {:assignee => user, :issues => user_issues(user, status)} %>
        <% end %>
        <% ordered_assignees.sort! { |a, b| b[:issues].length <=> a[:issues].length } %>

        <% ordered_assignees.each do |hash| %>
            <% user = hash[:assignee] %>
            <% issues = hash[:issues] %>
            <div class="user-issues user-id-<%= user ? user.id : "" %>">
              <h3 class="title"><%= user_section_title(user, status) %></h3>
              <% issues.each do |issue| %>
                  <table class="kanban_issue_table">
                    <tr id="issue-<%= h issue.id %>" class="hascontextmenu">
                      <td>
                        <%= check_box_tag("ids[]", issue.id, false, :id => nil, :style => "display:none;") %>
                  <div class="issue issue-<%= h issue.id %> issue-priority-<%= issue.priority.position %> issue-tracker-<%= slugalize(issue.tracker.name) %>">
                    <div class="issue-id"><%= link_to issue.id, {:controller => 'issues', :action => 'show', :id => issue.id} %></div>
                    <% if issue.estimated_hours %>
                        <div class="estimate time"><%= h hour_format(issue.estimated_hours).to_s.sub(/\.0$/, '') %></div>
                    <% end %>
                    <p><%= h issue.subject %></p>
                  </div>
                      </td>
                    </tr>
                  </table>
              <% end %>
            </div>
        <% end %>
      </div>
  <% end %>
</div>
<% end %>
  <%= context_menu issues_context_menu_path %>